% 05.06.19
% hard-drive filling up, so writing this to remove unnecessary data
% generated by afni_proc
clear all; close all; clc

%
origPath=pwd;
subjStrs={'S02','S03','S04','S05','S06','S07','S09','S10','S11','S12',...
    'S13','S14','S15','S16','S17','S18','S19','S20','S21','S22',...
    'S23','S24','S25','S26','S27','S28','S29','S30','S31','S32'};
nSubjects=numel(subjStrs);
for s=1:nSubjects
    subjStr=subjStrs{s};

    outputDir=['/Users/jacekdmochowski/PROJECTS/LLLT/data/output/' subjStr '/' subjStr '.results'];
    cd(outputDir)
    
    filename=['pb01.' subjStr '.r01.e03.tshift+orig.BRIK'];
    eval(['delete ' filename]);
    
    filename=['pb01.' subjStr '.r01.e02.tshift+orig.BRIK'];
    eval(['delete ' filename]);
    
    filename=['pb01.' subjStr '.r01.e01.tshift+orig.BRIK'];
    eval(['delete ' filename]);
    
    filename=['pb00.' subjStr '.r01.e03.tcat+orig.BRIK'];
    eval(['delete ' filename]);
    
    filename=['pb00.' subjStr '.r01.e02.tcat+orig.BRIK'];
    eval(['delete ' filename]);
    
    filename=['pb00.' subjStr '.r01.e01.tcat+orig.BRIK'];
    eval(['delete ' filename]);
    
    filename=['pb02.' subjStr '.r01.e01.volreg+orig.BRIK'];
    eval(['delete ' filename]);
    
    filename=['pb02.' subjStr '.r01.e02.volreg+orig.BRIK'];
    eval(['delete ' filename]);
    
    filename=['pb02.' subjStr '.r01.e03.volreg+orig.BRIK'];
    eval(['delete ' filename]);
    
        
    filename=['pb03.' subjStr '.r01.e01.combine+orig.BRIK'];
    eval(['delete ' filename]);
    
    filename=['pb04.' subjStr '.r01.e02.blur+orig.BRIK'];
    eval(['delete ' filename]);
    
    filename=['pb05.' subjStr '.r01.e03.scale+orig.BRIK'];
    eval(['delete ' filename]);
    
end