#!/bin/bash

afni_proc.py -subj_id S23                                		     \	
                  -dsets ./S23/bold_e2+orig.HEAD                              \
                  -blocks despike tshift align tlrc volreg blur mask         \
                          scale regress                                      \
                  -tcat_remove_first_trs 3                                   \
                  -tlrc_base MNI152_T1_2009c+tlrc                            \
                  -tlrc_NL_warp                                              \
                  -volreg_align_e2a                                          \
                  -volreg_tlrc_warp                                          \
                  -mask_epi_anat yes                                         \
                  -regress_censor_motion 0.2                                 \
                  -regress_censor_outliers 0.05                              \
                  -regress_bandpass 0.01 0.1                                 \
                  -regress_apply_mot_types demean deriv                      \
                  -regress_est_blur_epits                                    \
                  -regress_est_blur_errts			       \